- name: Install GitKraken
  snap:
    name: gitkraken
    classic: yes
  become: yes
- name: Install VS Code
  snap:
    name: code
    classic: yes
  become: yes
- name: Install Virtualbox
  apt:
    name: virtualbox
  become: yes
- name: Install sshpass
  apt:
    name: sshpass
  become: yes
- name: Install Ansible
  apt:
    name: ansible
  become: yes
- name: Uninstall Apache 2
  apt:
    name: apache2
    state: absent
  become: yes
- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes
# - name: Remove useless packages from the cache
#   apt:
#     autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes
