- name: Install GitKraken
  snap:
    name: gitkraken
    classic: yes
  become: yes
- name: Install VS Code
  snap:
    name: code
    classic: yes
  become: yes
- name: Install Virtualbox
  apt:
    name: virtualbox
  become: yes
- name: Install Ansible
  apt:
    name: ansible
  become: yes
- name: Uninstall Apache 2
- name: Install PHP
  apt:
    name: apache2
    state: absent
  become: yes
    - php
    - php-common
    - php-json
    - php-phpdbg
    - php-dev
    - php-xml
    - php-cli
    - libapache2-mod-php
    - php-mysql
    - php-gd
    - php-curl
    - php-mbstring
    - php-zip
    - php-pear
# - name: Add Docker CE key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
# - name: Add Docker CE repository
#   apt_repository:
#     repo: deb https://download.docker.com/linux/ubuntu eoan stable
#     filename: docker-ce
# - name: Install Docker CE
#   apt:
#     name: docker-ce
#     update_cache: yes
# - name: Add user to Docker group
#   user:
#     # name: '{{ user }}'
#     name: pavel
#     groups: docker
#     append: yes
# - name: Install docker-compose
#   apt:
#     name: docker-compose
#     update_cache: yes
# - name: Uninstall Apache 2
#   apt:
#     name: apache2
#     state: absent
# - name: Remove useless packages from the cache
#   apt:
#     autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes
